### ISSUE TITLE
[DRK] advanced mode aoe issues

### ISSUE THREAD

**Issue by hhharkness** [PunishXIV/WrathCombo#338]
ever since the update edge of shadow is showing up on the aoe advanced mode. there also doesn't seem to be an option to ignore range anymore

**Comment by zbee** [comment]
Edge use in AoE is already fixed in #336 

> an option to ignore range anymore

I don't know what you mean by this.

**Comment by hhharkness** [comment]
i misunderstood what was happening in the heat of battle - i thought it was telling me i was out of range for aoe skills but what's actually happening is that if the weaponskill combo is started syphon strike/souleater is showing up on the advanced aoe button

**Comment by Giblett** [comment]
To add onto this, Bloodspiller and Carve and Split are too, any delerium/spenders seem to be focusing on single target varients for AoE mode.

**Comment by zbee** [comment]
@Giblett those will also be fixed by #336 👍🏻 
The issue was in detecting the AoE flag, so it applied to anything AoE-specific, basically.

**Comment by hhharkness** [comment]
while the update did fix the single target skills showing up, unfortunately i'm still getting flood of shadow even with the option unchecked.

**Comment by zbee** [comment]
> i'm still getting flood of shadow even with the option unchecked.

@hhharkness Please make a new issue for this, with your debug file.
