### ISSUE TITLE
[War] Doesn't use Fel cleave / decimate based on fury

### ISSUE THREAD

**Issue by symposes** [PunishXIV/WrathCombo#517]
I have noticed that when using warrior now, the advanced mode doesn't seem to react to my fury gauge level at all. It only uses Cleave and Decimate, or their upgrades, when in Inner Fury. I normally don't hold any fury, but now it sits at 100 as much at it can.

![Image](https://github.com/user-attachments/assets/26ca8025-e898-4081-b171-d4e3d0c0096d)

**Comment by Kagekazu** [comment]
Known and fixed in 
<https://github.com/PunishXIV/WrathCombo/commit/3b62f295e98c72f8d46e632df48aa483d61b78a5>

**Comment by Netskia** [comment]
Still not working for me. Either in advanced mode nor automatic. Sometimes, It doesn't even consume beast gauge at all.

**Comment by Kagekazu** [comment]
> Still not working for me. Either in advanced mode nor automatic. Sometimes, It doesn't even consume beast gauge at all.

well it is not on live. it is merged, but not live
Hence why the problem is still open ^.^
